export default productsArray = [
  {
    productName: "Коляска 2в1 Anex M/Type Dune mt-01Q",
    quantityDiscount: "-15%",
    imageUrl: "./images/promotion/stroller.jpg",
    originalPrice: "6000 грн",
    discountedPrice: "5000 грн",
    manufacturer: "Anex",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Іграшка-головоломка Same Toy IQ Ball Cube",
    quantityDiscount: "-30%",
    imageUrl: "./images/promotion/ball.jpg",
    originalPrice: "300 грн",
    discountedPrice: "200 грн",
    manufacturer: "Bair",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Пляшечка 130 мл",
    quantityDiscount: "-25%",
    imageUrl: "./images/promotion/bottle.jpg",
    originalPrice: "150 грн",
    discountedPrice: "100 грн",
    manufacturer: "Carrello",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Суміш молочна суха Nutrilon",
    quantityDiscount: "-10%",
    imageUrl: "./images/promotion/foods.jpg",
    originalPrice: "350 грн",
    discountedPrice: "300 грн",
    manufacturer: "Nutrilon",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Автокрісло Maxi-Cosi Citi Concrete grey",
    quantityDiscount: "-20%",
    imageUrl: "./images/promotion/carseat.jpg",
    originalPrice: "4300 грн",
    discountedPrice: "3999 грн",
    manufacturer: "Babyroom",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Прогулянкова коляска Chicco Liteway 4",
    quantityDiscount: "-20%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/ff763a95aa66ca3e2a903d696473b598.jpg",
    originalPrice: "7300 грн",
    discountedPrice: "5999 грн",
    manufacturer: "Chicco",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Прогулянкова коляска Stokke Xplory X",
    quantityDiscount: "-20%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/1839a96cc8fa9ff67412a289f649a89f.jpg",
    originalPrice: "10300 грн",
    discountedPrice: "8999 грн",
    manufacturer: "Stokke",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Молочна вершкова вівсяна каша Kendamil, з 6 міс., 150 г",
    quantityDiscount: "-10%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/18d3f17dd5c55bf29e653decdbb8a478.jpg",
    originalPrice: "159 грн",
    discountedPrice: "89 грн",
    manufacturer: "Kendamil",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Молочна каша Kendamil з овочами, з 6 міс., 150 г",
    quantityDiscount: "-10%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/18d3f17dd5c55bf29e653decdbb8a478.jpg",
    originalPrice: "149 грн",
    discountedPrice: "99 грн",
    manufacturer: "Kendamil",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName:
      "Органічна суха молочна суміш Kendamil Organic 3, 12-36 міс., 800 г",
    quantityDiscount: "-10%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/f1c1bfa93024f3b1ccdee6d250067396.jpg",
    originalPrice: "349 грн",
    discountedPrice: "299 грн",
    manufacturer: "Kendamil",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName:
      "Органічна суха молочна суміш Kendamil Organic 3, 12-36 міс., 800 г",
    quantityDiscount: "-10%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/53a6e3edce6d7c8546c216b296712c85.jpg",
    originalPrice: "949 грн",
    discountedPrice: "859 грн",
    manufacturer: "Kendamil",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Пляшечка скло Chicco Natural Feeling NEW, 150 мл, 0м+",
    quantityDiscount: "-10%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/8df81c68a6bb83967624626fc3ccbb1f.jpeg",
    originalPrice: "349 грн",
    discountedPrice: "259 грн",
    manufacturer: "Chicco",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Стільчик для годування 3 в 1 Chicco Crescendo Up",
    quantityDiscount: "-20%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/22d90d713f34cb461a1d8706a7ae11a9.jpg",
    originalPrice: "6349 грн",
    discountedPrice: "5559 грн",
    manufacturer: "Chicco",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Сидіння-бустер 2 в 1 Ingenuity Baby Base",
    quantityDiscount: "-10%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/22d90d713f34cb461a1d8706a7ae11a9.jpg",
    originalPrice: "1349 грн",
    discountedPrice: "1259 грн",
    manufacturer: "Ingenuity",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Пустушка Chicco Physio Soft, силікон, 0-6 міс.,1 шт.",
    quantityDiscount: "-20%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/420ec77dad4dcee4ddc3461604fc4568.jpg",
    originalPrice: "149 грн",
    discountedPrice: "119 грн",
    manufacturer: "Ingenuity",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Автокрісло Chicco Unico Plus, група 0+/1/2/3",
    quantityDiscount: "-20%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/c80faf043188baa835f804ad9a350b62.jpg",
    originalPrice: "10049 грн",
    discountedPrice: "9119 грн",
    manufacturer: "Chicco",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Автокрісло Britax Römer Dualfix i-Size, група 0+/1",
    quantityDiscount: "-20%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/c80faf043188baa835f804ad9a350b62.jpg",
    originalPrice: "9049 грн",
    discountedPrice: "8119 грн",
    manufacturer: "Britax",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: "Автокрісло Stokke iZi Go Modular™ X1 by BeSafe®, група 0+",
    quantityDiscount: "-10%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/0e7ae65215b3bfa69afa4a90ae4d6e96.jpg",
    originalPrice: "11049 грн",
    discountedPrice: "9119 грн",
    manufacturer: "Britax",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: 'Машинка музична Chicco "Вантажівка Turbo Ball"',
    quantityDiscount: "-10%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/b1c66f5dd75951971fd86100af5bc7f5.jpg",
    originalPrice: "1049 грн",
    discountedPrice: "919 грн",
    manufacturer: "Britax",
    status: "В наявності",
    productCode: "EP-01",
  },
  {
    productName: 'Ігровий центр Chicco "Пожежна станція Turbo Ball"',
    quantityDiscount: "-10%",
    imageUrl:
      "https://static.ma.com.ua/images/1000xAUTO/181a38a59dd35aa1cd8d05f83866d9ac.jpg",
    originalPrice: "1049 грн",
    discountedPrice: "819 грн",
    manufacturer: "Britax",
    status: "В наявності",
    productCode: "EP-01",
  },
];
